# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build the alpine and debian versions.
- name: 'gcr.io/cloud-builders/git'
  args: ['log']
